#!/usr/bin/env bash
# Configures a new Ubuntu machine with Nginx and a custom HTTP response header

sudo apt-get update -y
sudo apt-get install nginx -y

# Add the custom X-Served-By header to the Nginx default configuration
sudo sed -i '/listen 80 default_server;/a \ \ \ \ \ \ \ \ add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default

sudo service nginx restart
