#!/usr/bin/env bash
# Configures a new Ubuntu machine with Nginx and a custom HTTP response header

# Update package lists
apt-get update -y

# Install nginx
apt-get install -y nginx

# Set up standard custom index text from previous project task
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

# Inject custom HTTP header X-Served-By with the server's current hostname
# We use sed to insert it inside the HTTP configuration block
sed -i "/http {/a \\\tadd_header X-Served-By \$hostname;" /etc/nginx/nginx.conf

# Restart Nginx safely without systemctl
service nginx restart