#!/usr/bin/env bash
# Configures a new Ubuntu machine with HAProxy to distribute traffic to web servers

# Update package lists
apt-get update -y

# Install HAProxy
apt-get install -y haproxy

# Enable HAProxy init script management
echo "ENABLED=1" > /etc/default/haproxy

# Configure HAProxy routing block
cat <<EOF >> /etc/nginx/../haproxy/haproxy.cfg

frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    balance roundrobin
    mode http
    server 7112-web-01 44.203.111.212:80 check
    server 7112-web-02 44.204.52.194:80 check
EOF

# Restart HAProxy safely using service init script style
service haproxy restart