#!/usr/bin/env bash
# Installs and configures HAProxy to load balance traffic between mock servers

sudo apt-get update -y
sudo apt-get install haproxy -y
sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy

sudo cat << 'HAPROXY' >> /etc/haproxy/haproxy.cfg

frontend alu_frontend
    bind *:80
    mode http
    default_backend alu_backend

backend alu_backend
    balance roundrobin
    mode http
    server web-01 3.93.38.36:8000 check
    server web-02 3.93.38.36:8080 check
HAPROXY

sudo service haproxy restart
