#!/usr/bin/env bash
# Installs and configures HAProxy to load balance traffic between web-01 and web-02

sudo apt-get update -y
sudo apt-get install haproxy -y
sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy

sudo cat << 'HAPROXY' >> /etc/haproxy/haproxy.cfg

frontend alu_frontend
    bind *:80
    mode http
    default_backend alu_backend

backend alu_backend
    balance roundrobin
    mode http
    server web-01 34.237.242.75:80 check
    server web-02 32.198.91.240:80 check
HAPROXY

sudo service haproxy restart
