#!/usr/bin/env bash
# Transfers a file from our local machine to a remote server
if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME [PATH_TO_SSH_KEY]"
    exit 1
fi
PATH_TO_FILE=$1
IP=$2
USERNAME=$3
SSH_KEY=$4
if [ -n "$SSH_KEY" ]; then
    scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
else
    scp -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
fi
