#!/usr/bin/env bash
# Configures a new Ubuntu machine to install Nginx listening on port 80

apt-get update -y
apt-get install -y nginx

# Overwrite the default Nginx index file to contain the exact required string
echo "Holberton School" > /var/www/html/index.nginx-debian.html

# Restart Nginx without using systemctl
service nginx restart
